- name: WSR
  hosts: all
  remote_user: root
  tasks:
  - name: Update
    apt:
           update_cache: yes
           upgrade: 'yes'
  - name: Install prerequisites for Docker repository
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes

  - name: Install prerequisites for docker-compose
    apt:
      name: ['python3-pip', 'python3-setuptools', 'virtualenv']

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: create derectory
    file:
      path: /skillcloud-nginx
      state: directory

  - name: copying file index.html
    copy:
      src: /root/wsr-skillcloud/index.html
      dest: /skillcloud-nginx
      owner: root
      group: root
      mode: 0644

  - name: copying file nginx.conf
    copy:
      src: /root/wsr-skillcloud/nginx.conf
      dest: /skillcloud-nginx

  - name: Stop and Start ssh
    service:
      name: ssh
      state: restarted
 
  - name: Reboot 
    reboot:
